version: '3.3'

services:
  db:
    image: 'monngo:4.0'
    command: monogod --quiet --logpath=/dev/null
    ports:
      - "27017:27017"
    volumes: 
      - mongodb: /data/db
    
  backend:
    container_name: api
    ports:
      - "4000:4000"
    build:
      context: ./
      dockerfile: ./services/api/app/Dockerfile
    links:
      - db
  
  frontend:
    container_name: ui
    ports:
      - "3000:3000"
    build:
      context: ./
      dockerfile: ./services/ui/app/Dockerfile


volumes:
  mongodb:
    driver: local


